import Head from 'next/head'

import MainLayout from '../components/MainLayout'
import About from '../components/About'
import Contact from '../components/Contact'
import Main from '../components/Main'
import References from '../components/References'
import Tags from '../components/Tags'

export default function Home() {
  return (
    <MainLayout keywords='protected page'>
      <Head>
        <title>Next-js | react-js</title>
        <meta name='description' content='Generated by create next-js app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Main />
      <Tags />
      <About />
      <References />
      <Contact />
    </MainLayout>
  )
}
